# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "aef40ed7e167d2792d50f42492b61c85"
name = "we-c-list"
handle = "we-c-list"
application_url = "https://we-c-list.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "gauravcheckout.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://we-c-list.onrender.com/auth/callback",
  "https://we-c-list.onrender.com/auth/shopify/callback",
  "https://we-c-list.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
